### ISSUE TITLE
Enable color on Travis CI and AppVeyor

### ISSUE THREAD

**Issue by krlmlr** [r-pkgs/crayon#52]
They support it now: https://travis-ci.org/hadley/colformat#L1313

AppVeyor: https://github.com/appveyor/ci/issues/373

**Comment by gaborcsardi** [comment]
How about forcing it with an environment variable?

**Comment by krlmlr** [comment]
I'd prefer if crayon just worked. Otherwise users would have to clutter their .travis.yml and appveyor.yml.

Use case: https://github.com/ropenscilabs/tic/issues/5.

**Comment by gaborcsardi** [comment]
On Travis the output is written to files, and then if you read these files programatically, or download them from Travis, they will contain the ANSI characters.

If you need to turn on colors for testing, you can always do that with `options(crayon.enabled = TRUE); options(crayon.colors = 256)`.

**Comment by gaborcsardi** [comment]
I am just afraid that turning it on will actually cause confusion.

**Comment by krlmlr** [comment]
I'd like to use color to highlight terminal output, but I can work around for my particular use case. I see how this can break in unexpected ways.

Maybe if we had a `force = FALSE` argument to each style function?

**Comment by krlmlr** [comment]
No, that won't work either... Thanks anyway for considering.
